---
# The plays for zookeper daemons

- name: Install the zookeeper files
  yum: name=zookeeper-server state=installed

- name: Copy the configuration file for zookeeper
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify: restart zookeeper

- name: initialize the zookeper
  shell: creates=/var/lib/zookeeper/myid service zookeeper-server init --myid=${zoo_id}
 
