---
# Handlers for the hadoop slave services

- name: restart hadoop slave services
  service: name=${item} state=restarted
  with_items: 
    - hadoop-0.20-mapreduce-tasktracker
    - hadoop-hdfs-datanode
