---
# tasks for the bind server

- name: Install the bind packages
  yum: name={{ item }} state=installed
  with_items:
   - bind
   - bind-utils

- name: Copy the key for dynamic dns updates to the domain
  template: src=keyfile.j2 dest=/var/named/{{ domain_name }}.key owner=named group=named

- name: Copy the forwarders file for bind
  template: src=forwarders.conf.j2 dest=/var/named/forwarders.conf owner=named group=named

- name: copy the db file for the domain
  template: src=domain.db.j2 dest=/var/named/dynamic/{{ domain_name }}.db owner=named group=named  

- name: copy the named.conf file 
  template: src=named.conf.j2 dest=/etc/named.conf owner=root group=named mode=755 
  notify: restart named

- name: restore the sellinux contexts
  shell: restorecon -v /var/named/forwarders.conf; restorecon -rv /var/named; restorecon /etc/named.conf; touch /opt/named.init
         creates=/opt/named.init

