---
# Tasks for the Openshift broker installation

- name: Install mcollective
  yum: name=mcollective-client

- name: Copy the mcollective configuration file
  template: src=client.cfg.j2 dest=/etc/mcollective/client.cfg

- name: Install the broker components
  yum: name="{{ item }}" state=installed
  with_items: "{{ broker_packages }}"

- name: Copy the rhc client configuration file
  template: src=express.conf.j2 dest=/etc/openshift/express.conf
  register: last_run

- name: Install the gems for rhc
  script: gem.sh 
  when: last_run.changed

- name: create the file for mcollective logging
  copy: content="" dest=/var/log/mcollective-client.log owner=apache group=root

- name: SELinux - configure sebooleans
  seboolean:  name="{{ item }}" state=true persistent=yes
  with_items:
      - httpd_unified
      - httpd_can_network_connect
      - httpd_can_network_relay 
      - httpd_run_stickshift
      - named_write_master_zones 
      - httpd_verify_dns
      - allow_ypbind

- name: copy the auth keyfiles
  copy: src="{{ item }}" dest="/etc/openshift/{{ item }}"
  with_items:
      - server_priv.pem
      - server_pub.pem
      - htpasswd

- name: copy the local ssh keys
  copy: src="~/.ssh/{{ item }}" dest="~/.ssh/{{ item }}"
  with_items:
      - id_rsa.pub
      - id_rsa

- name: copy the local ssh keys to openshift dir
  copy: src="~/.ssh/{{ item }}" dest="/etc/openshift/rsync_{{ item }}"
  with_items:
      - id_rsa.pub
      - id_rsa

- name: Copy the broker configuration file
  template: src=broker.conf.j2 dest=/etc/openshift/broker.conf

- name: create the file for ssl.conf
  copy: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf owner=apache group=root

- name: copy the configuration file for openstack plugins
  template: src="{{ item }}" dest="/etc/openshift/plugins.d/{{ item }}"
  with_items:
      - openshift-origin-auth-remote-user.conf
      - openshift-origin-dns-bind.conf
      - openshift-origin-msg-broker-mcollective.conf

- name: Bundle the ruby gems
  shell: chdir=/var/www/openshift/broker/ /usr/bin/scl enable ruby193 "bundle show"; touch bundle.init
         creates=//var/www/openshift/broker/bundle.init

- name: Copy the httpd configuration file
  copy: src=openshift-origin-auth-remote-user.conf dest=/var/www/openshift/broker/httpd/conf.d/openshift-origin-auth-remote-user.conf

- name: Fix the selinux contexts on several files
  shell: fixfiles -R rubygem-passenger restore; fixfiles -R mod_passenger restore; restorecon -rv /var/run; restorecon -rv /usr/share/rubygems/gems/passenger-*; touch /opt/context.fixed  creates=/opt/context.fixed

- name: start the http and broker service
  service: name="{{ item }}" state=started enabled=yes
  with_items:
      - httpd
      - openshift-broker
 
