---
# The playbook for common tasks

- name: Deploy the Cloudera Repository
  copy: src=etc/cloudera-CDH4.repo dest=/etc/yum.repos.d/cloudera-CDH4.repo

- name: Install the openjdk package
  yum: name=java-1.6.0-openjdk state=installed

- name: create a directory for java 
  file:  state=directory path=/usr/java/

- name: create a link for java
  file: src=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre state=link path=/usr/java/default

- name: Create the hosts file for all machines
  template: src=etc/hosts.j2 dest=/etc/hosts

- name: Disable SELinux in conf file
  lineinfile: dest=/etc/sysconfig/selinux regexp='^SELINUX=' line='SELINUX=disabled' state=present

- name: Disabel selinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled

- name: Create the iptables file for all machines
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

