---
# Common tasks across nodes

- name: Install common packages
  yum : name={{ item }} state=installed
  with_items:
   - libselinux-python
   - policycoreutils
   - policycoreutils-python
   - ntp
   - ruby-devel

- name: make sure we have the right time
  shell: ntpdate -u 0.centos.pool.ntp.org

- name: start the ntp service
  service: name=ntpd state=started enabled=yes

- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts

- name: Create the EPEL Repository.
  copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

- name: Create the OpenShift Repository.
  copy: src=openshift.repo dest=/etc/yum.repos.d/openshift.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: SELinux Enforcing (Targeted)
  selinux: policy=targeted state=enforcing

- name: copy the file for ruby193 profile
  copy: src=scl193.sh dest=/etc/profile.d/scl193.sh mode=755    

- name: copy the file for mcollective profile
  copy: src=scl193.sh dest=/etc/sysconfig/mcollective mode=755    

- name: Create the iptables file
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables 
