---
# This role deploys the mongod processes and sets up the replication set.


- name: Install the mongodb package
  yum: name={{ item }} state=installed
  with_items:
   - mongodb
   - mongodb-server
   - bc
   - python-pip
   - gcc

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no 

- name: Create the data directory for mongodb
  file: path={{ mongodb_datadir_prefix }} owner=mongodb group=mongodb state=directory

- name: Copy the keyfile for authentication
  copy: src=secret dest={{ mongodb_datadir_prefix }}/secret owner=mongodb group=mongodb mode=0400

- name: Create the mongodb configuration file
  template: src=mongod.conf.j2 dest=/etc/mongodb.conf

- name: Start the mongodb service
  service: name=mongod state=started

- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest=/tmp/repset_init.js

- name: Pause for a while
  wait_for: port="{{ mongod_port }}" delay=30

- name: Initialize the replication set
  shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js;touch /opt/rep.init creates=/opt/rep.init
  when: inventory_hostname ==  groups['mongo_servers'][0]

- name: add the admin user
  mongodb_user: database=admin name=admin password={{ mongo_admin_pass }} login_port={{ mongod_port }} state=present
  when: inventory_hostname ==  groups['mongo_servers'][0]
  ignore_errors: yes

