---
# variables for broker

broker_packages:
   - mongodb-devel
   - openshift-origin-broker 
   - openshift-origin-broker-util
   - rubygem-openshift-origin-dns-nsupdate
   - rubygem-openshift-origin-auth-mongo
   - rubygem-openshift-origin-auth-remote-user
   - rubygem-openshift-origin-controller 
   - rubygem-openshift-origin-msg-broker-mcollective 
   - rubygem-openshift-origin-dns-bind
   - rubygem-passenger
   - mod_passenger
   - mysql-devel
   - rhc
   - ruby193-rubygem-actionmailer
   - ruby193-rubygem-actionpack
   - ruby193-rubygem-activemodel
   - ruby193-rubygem-activerecord
   - ruby193-rubygem-activeresource
   - ruby193-rubygem-activesupport
   - ruby193-rubygem-arel
   - ruby193-rubygem-bigdecimal
   - ruby193-rubygem-net-ssh
   - ruby193-rubygem-commander
   - ruby193-rubygem-archive-tar-minitar
   - ruby193-rubygem-bson
   - ruby193-rubygem-bson_ext
   - ruby193-rubygem-builder
   - ruby193-rubygem-bundler
   - ruby193-rubygem-cucumber
   - ruby193-rubygem-diff-lcs
   - ruby193-rubygem-dnsruby
   - ruby193-rubygem-erubis
   - ruby193-rubygem-gherkin
   - ruby193-rubygem-hike
   - ruby193-rubygem-i18n
   - ruby193-rubygem-journey
   - ruby193-rubygem-json
   - ruby193-rubygem-mail
   - ruby193-rubygem-metaclass
   - ruby193-rubygem-mime-types
   - ruby193-rubygem-minitest
   - ruby193-rubygem-mocha
   - ruby193-rubygem-mongo
   - ruby193-rubygem-mongoid
   - ruby193-rubygem-moped
   - ruby193-rubygem-multi_json
   - ruby193-rubygem-open4
   - ruby193-rubygem-origin
   - ruby193-rubygem-parseconfig
   - ruby193-rubygem-polyglot
   - ruby193-rubygem-rack
   - ruby193-rubygem-rack-cache
   - ruby193-rubygem-rack-ssl
   - ruby193-rubygem-rack-test
   - ruby193-rubygem-rails
   - ruby193-rubygem-railties
   - ruby193-rubygem-rake
   - ruby193-rubygem-rdoc
   - ruby193-rubygem-regin
   - ruby193-rubygem-rest-client
   - ruby193-rubygem-simplecov
   - ruby193-rubygem-simplecov-html
   - ruby193-rubygem-sprockets
   - ruby193-rubygem-state_machine
   - ruby193-rubygem-stomp
   - ruby193-rubygem-systemu
   - ruby193-rubygem-term-ansicolor
   - ruby193-rubygem-thor
   - ruby193-rubygem-tilt
   - ruby193-rubygem-treetop
   - ruby193-rubygem-tzinfo
   - ruby193-rubygem-xml-simple
  
   

auth_salt: "ceFm8El0mTLu7VLGpBFSFfmxeID+UoNfsQrAKs8dhKSQ/uAGwjWiz3VdyuB1fW/WR+R1q7yXW+sxSm9wkmuqVA=="
session_secret: "25905ebdb06d8705025531bb5cb45335c53c4f36ee534719ffffd0fe28808395d80449c6c69bc079e2ac14c8ff66639bba1513332ef9ad5ed42cc0bb21e07134"

