
- hosts: all
  user: root
  roles:
      - role: common

- hosts: dns
  user: root
  roles:
      - role: dns
- hosts: mongo_servers
  user: root
  roles:
      - role: mongodb

- hosts: mq
  user: root
  roles:
      - role: mq

- hosts: broker
  user: root
  roles:
   - role: broker

- hosts: nodes
  user: root
  roles:
   - role: nodes

- hosts: lvs
  user: root
  roles:
   - role: lvs
