---
# The mail include file  for the controller node

- include: base.yml
- include: keystone.yml
- include: glance.yml
- include: nova.yml
- include: cinder.yml
- include: horizon.yml
- include: quantum.yml

